import winston, { format } from "winston";
import { DateTime } from "luxon";
import path from "path";
import * as fs from "fs";
import { loggerConfig, LOG_LEVELS, CONSOLE_COLORS } from "./Logger.config.js";
import type { LogLevel } from "./types/logger.type.js";
import type { EnvironmentStage } from "../../../environment/environment.constants.js";

export default class LoggerFactory {
  private static directoryEnsured = false;

  /**
   * Creates a winston logger instance with the configured transports and exception handlers.
   * Before creating the logger, it ensures the log directory exists.
   * @returns {winston.Logger} The created winston logger instance.
   */
  public static createLogger(): winston.Logger {
    this.ensureLogDirectoryExists();

    return winston.createLogger({
      level: "debug",
      transports: [
        ...this.createFileTransports(),
        this.createConsoleTransport(),
      ],
      exceptionHandlers: [this.createCustomHandler("exceptions.log")],
      rejectionHandlers: [this.createCustomHandler("rejections.log")],
    });
  }

  /**
   * Ensures the log directory exists.
   * If the directory does not exist, it is created recursively.
   * If an error occurs during directory creation, an error is thrown.
   */
  public static ensureLogDirectoryExists(): void {
    if (this.directoryEnsured) {
      return;
    }

    const { directory } = loggerConfig;

    try {
      if (!fs.existsSync(directory)) {
        fs.mkdirSync(directory, { recursive: true });
      }
      this.directoryEnsured = true;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      throw new Error(
        `Failed to create log directory at ${directory}: ${errorMessage}`,
      );
    }
  }

  /**
   * Creates an array of file transports, one for each log level.
   * Each file transport is configured with a maximum file size,
   * a filename resolved from the logger config, the corresponding log level,
   * and a format combining timestamp, log level, and message.
   * The base configuration is generated by createBaseTransportConfig().
   * The resolved filename is generated by resolvePath() using the logger config filename.
   * The format is generated by createLevelFormat() using the base configuration and log level.
   * @returns {winston.transports.FileTransportInstance[]} An array of file transports, one for each log level.
   */
  private static createFileTransports(): winston.transports.FileTransportInstance[] {
    const baseConfig = this.createBaseTransportConfig();

    return LOG_LEVELS.map(
      (level) =>
        new winston.transports.File({
          maxsize: baseConfig.maxFileSize,
          filename: this.resolvePath(loggerConfig.files[level]),
          level,
          format: this.createLevelFormat(level, baseConfig),
        }),
    );
  }

  /**
   * Creates a base configuration object for winston transports.
   * This base configuration is used by both file and console transports.
   *
   * @returns {object} An object containing the base configuration for winston transports.
   * @property {number} maxFileSize The maximum file size in bytes before log rotation.
   * @property {string} timestamp The timestamp format string compatible with winston's timestamp format.
   * @property {string} print The print format string compatible with winston's print format.
   */
  private static createBaseTransportConfig() {
    return {
      maxFileSize: loggerConfig.maxFileSize,
      timestamp: this.buildTimestampFormat(),
      print: this.buildPrintFormat(),
    };
  }

  /**
   * Combines levelFilter(), uncolorize(), timestamp, and print formats
   * to produce a format suitable for use in a winston transport.
   *
   * @param {LogLevel} level The log level that this format should filter for.
   * @param {ReturnType<typeof LoggerFactory.createBaseTransportConfig>} baseConfig The base configuration for the transport.
   *
   * @returns {winston.Logform.Format} A format suitable for use in a winston transport.
   */
  private static createLevelFormat(
    level: LogLevel,
    baseConfig: ReturnType<typeof LoggerFactory.createBaseTransportConfig>,
  ): winston.Logform.Format {
    return winston.format.combine(
      this.levelFilter(level),
      winston.format.uncolorize(),
      baseConfig.timestamp,
      baseConfig.print,
    );
  }

  /**
   * Creates a console transport configured for the current environment.
   * The log level is determined by calling resolveConsoleLevel() with the current environment.
   * The format combines a timestamp, coloring using CONSOLE_COLORS, and a plain print format.
   *
   * @private
   * @returns {winston.transports.ConsoleTransportInstance} A console transport configured for the current environment.
   */
  private static createConsoleTransport(): winston.transports.ConsoleTransportInstance {
    const environment = (process.env.ENV as EnvironmentStage) ?? "dev";

    return new winston.transports.Console({
      level: this.resolveConsoleLevel(environment),
      format: winston.format.combine(
        this.buildTimestampFormat(),
        winston.format.colorize({ colors: CONSOLE_COLORS }),
        this.buildPrintFormat(),
      ),
    });
  }

  /**
   * Creates a custom file transport for exception and rejection handlers.
   * File path is resolved using the loggerConfig.directory.
   *
   * @private
   * @param {string} filename - The name of the file to write to.
   * @returns {winston.transports.FileTransportInstance} A custom file transport.
   */
  private static createCustomHandler(
    filename: string,
  ): winston.transports.FileTransportInstance {
    return new winston.transports.File({
      filename: this.resolvePath(filename),
      format: winston.format.combine(
        winston.format.uncolorize(),
        this.buildTimestampFormat(),
        this.buildPrintFormat(),
      ),
    });
  }

  /**
   * Map of environment stages to console log levels.
   */
  private static readonly consoleLevelMap: Record<EnvironmentStage, LogLevel> =
    {
      dev: "debug",
      qa: "debug",
      uat: "info",
      preprod: "warn",
      prod: "error",
    };

  /**
   * Resolves the console log level for a given environment.
   * If the environment is not recognized, defaults to "debug".
   * @param {EnvironmentStage} environment The environment to resolve the console log level for.
   * @returns {LogLevel} The resolved console log level.
   */
  private static resolveConsoleLevel(environment: EnvironmentStage): LogLevel {
    return this.consoleLevelMap[environment] ?? "debug";
  }

  /**
   * Creates a winston log format that filters log entries based on their level.
   * If the log entry's level matches the provided level, the entry is passed through unchanged.
   * Otherwise, the entry is replaced with false, effectively filtering it out.
   * @param {LogLevel} level The log level to filter by
   * @returns {winston.Logform.Format} A winston log format that filters log entries by level
   */
  private static levelFilter(level: LogLevel): winston.Logform.Format {
    return format((info) => (info.level === level ? info : false))();
  }

  /**
   * Builds a timestamp format for winston logs.
   * Uses Luxon DateTime to format the timestamp according to loggerConfig.dateFormat
   * and loggerConfig.timeZone.
   * The output format is: `[timestamp]`
   * Used by both file and console transports to format log entries before writing to disk or console.
   * @private
   * @returns {winston.Logform.Format} A log format combining timestamp.
   */
  private static buildTimestampFormat(): winston.Logform.Format {
    return winston.format.timestamp({
      format: () =>
        DateTime.now()
          .setZone(loggerConfig.timeZone)
          .toFormat(loggerConfig.dateFormat),
    });
  }

  /**
   * Creates a log format combining timestamp, log level and message.
   * The output format is: `[timestamp] [level]: message`
   * Used by file transports to format log entries before writing to disk.
   * @private
   * @returns {winston.Logform.Format} A log format combining timestamp, log level and message.
   */
  private static buildPrintFormat(): winston.Logform.Format {
    return winston.format.printf(
      ({ level, message, timestamp }: winston.Logform.TransformableInfo) =>
        `${timestamp as string} [${level}]: ${message as string}`,
    );
  }

  /**
   * Resolves a file name to a full path within the configured log directory.
   * Used by file transports to determine the output file name.
   * @private
   */
  private static resolvePath(fileName: string): string {
    return path.join(loggerConfig.directory, fileName);
  }
}
