import EnvironmentDetector from "../detector/environmentDetector.js";
import EnvironmentConfigManager from "../manager/environmentConfigManager.js";
import EnvironmentVariables from "../variables/environmentVariables.js";
import type { Credentials } from "../../authentication/types/credentials.types.js";
import type { AuthRole } from "../../authentication/storage/internal/authentication.constants.js";
import ErrorHandler from "../../../utils/errorHandling/errorHandler.js";

export class RuntimeEnvVariableResolver {
  /**
   * Indicates if the application is running in a CI environment
   */
  private readonly isCI = EnvironmentDetector.isCI();

  /**
   * Retrieves the portal base URL.
   * In a CI environment, this function will return the portal base URL set as an environment variable.
   * Otherwise, it will return the portal base URL set in the local environment variables.
   * @returns The portal base URL
   * @throws Error - If the portal base URL is not set or invalid
   */
  public getPortalBaseUrl(): string {
    try {
      return this.isCI
        ? process.env.CI_PORTAL_BASE_URL!
        : this.resolveLocalVariable(
            () => EnvironmentVariables.urls.PORTAL_BASE_URL,
            "Portal Base URL",
          );
    } catch (error) {
      ErrorHandler.captureError(
        error,
        "getPortalBaseUrl",
        "Failed to get portal base URL",
      );
      throw error;
    }
  }

  /**
   * Gets the portal credentials for a given user role.
   * If running in a CI environment, this function returns the credentials for the given user role
   * by looking up the environment variables that contain the credentials.
   * If not running in a CI environment, this function first extracts the username and password for the given role from the environment variables.
   * It then decrypts the extracted credentials using the environment's secret key.
   * @param role - The user role to get the portal credentials for
   * @returns A promise that resolves with the portal credentials for the given user role
   * @throws Error - If the portal credentials cannot be resolved, an error with additional information is thrown
   */
  public async getPortalCredentials(role: AuthRole): Promise<Credentials> {
    try {
      return this.isCI
        ? this.resolveCICredentials(role)
        : this.resolveLocalCredentials(role);
    } catch (error) {
      ErrorHandler.captureError(
        error,
        "getPortalCredentials",
        "Failed to get portal credentials",
      );
      throw error;
    }
  }

  /**
   * Resolves the credentials for a given user role in a CI environment.
   * In a CI environment, this function returns the credentials for the given user role
   * by looking up the environment variables that contain the credentials.
   * @param role - The user role to resolve the credentials for
   * @returns The resolved credentials for the given user role
   */
  private resolveCICredentials(role: AuthRole): Credentials {
    const envVars: Record<AuthRole, { username: string; password: string }> = {
      ADMIN: {
        username: process.env.CI_PORTAL_ADMIN_USERNAME!,
        password: process.env.CI_PORTAL_ADMIN_PASSWORD!,
      },
      GENERAL: {
        username: process.env.CI_PORTAL_GENERAL_USERNAME!,
        password: process.env.CI_PORTAL_GENERAL_PASSWORD!,
      },
    };

    return EnvironmentConfigManager.verifyCredentials(envVars[role]);
  }

  /**
   * Resolves the local credentials for a given user role.
   * This function first extracts the username and password for the given role from the environment variables.
   * It then decrypts the extracted credentials using the environment's secret key.
   * @param role - The user role to resolve the local credentials for
   * @returns The resolved local credentials for the given user role
   */
  private async resolveLocalCredentials(role: AuthRole): Promise<Credentials> {
    const envVars: Record<AuthRole, { username: string; password: string }> = {
      ADMIN: {
        username: EnvironmentVariables.credentials.PORTAL_ADMIN_USERNAME,
        password: EnvironmentVariables.credentials.PORTAL_ADMIN_PASSWORD,
      },
      GENERAL: {
        username: EnvironmentVariables.credentials.PORTAL_GENERAL_USERNAME,
        password: EnvironmentVariables.credentials.PORTAL_GENERAL_PASSWORD,
      },
    };

    const { username, password } = envVars[role];
    return this.decryptCredentials(username, password);
  }

  // Helpers

  /**
   * Resolves a local variable using the given description.
   * The description is used to generate a key and method name for retrieving the variable.
   * The method name is generated by prepending "get" to the description with all whitespace removed.
   * The key is generated by converting the description to lowercase and removing all whitespace.
   * The variable value is retrieved using EnvironmentConfigManager.getEnvironmentVariable.
   * @param getValue - A function that returns the variable value
   * @param description - A description of the variable
   * @returns The variable value
   */
  private resolveLocalVariable<T>(getValue: () => T, description: string): T {
    const key = description.toLowerCase().replace(/\s+/g, "");
    const method = `get${description.replace(/\s+/g, "")}`;
    const errorMessage = `Failed to get ${description.toLowerCase()}`;

    return EnvironmentConfigManager.getEnvironmentVariable(
      getValue,
      key,
      method,
      errorMessage,
    );
  }

  /**
   * Decrypts the given username and password using the current environment secret key
   * @param username - The username to decrypt
   * @param password - The password to decrypt
   * @returns A promise resolving to the decrypted credentials
   * @throws Error if the username or password is invalid
   */
  private async decryptCredentials(
    username: string,
    password: string,
  ): Promise<Credentials> {
    EnvironmentConfigManager.verifyCredentials({ username, password });

    return EnvironmentConfigManager.decryptCredentials(
      username,
      password,
      EnvironmentConfigManager.getCurrentEnvSecretKey(),
    );
  }
}
